# You may have to execute each of these 3 commands seperatly

CREATE TABLE `DataFile_Pool` (
	`DataFileID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Active`	INTEGER NOT NULL,
	`SD`	INTEGER NOT NULL,
	`MD5_Hash`	TEXT NOT NULL UNIQUE,
	`FileName`	TEXT NOT NULL,
	`DateTime`	TEXT NOT NULL
)

CREATE TABLE "ResultEntry" (
	`ResultID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserID`	INTEGER NOT NULL,
	`DataFileID`	INTEGER NOT NULL,
	`UserEnrtySD`	INTEGER NOT NULL,
	`CorrectSD`	INTEGER NOT NULL,
	`ConfidenceLevel`	INTEGER NOT NULL,
	`DateTime`	TEXT NOT NULL,
	`Notes`	TEXT
)

CREATE TABLE "Users" (
	`UserID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FullName`	TEXT NOT NULL UNIQUE,
	`DateTime`	TEXT NOT NULL
)